### ISSUE TITLE
Initial setup doesn't migrate DB

### ISSUE THREAD

**Issue by maiamcc** [harrislapiroff/politweets#4]
Either initial setup instructions don't include DB setup (`... manage.py migrate`) and should, or else this is supposed to happen somewhere in the setup code and isn't happening.

Either way, I followed the instructions in the README and hit errors when trying to `sync_members` b/c my DB didn't have the necessary tables. Problem went away when I ran
```
docker-compose exec django pipenv run ./manage.py migrate
```

**Comment by harrislapiroff** [comment]
Resolved in d9fc9d30649014e8fd3896dbfc3867330750e41b
